Repository PapKate/SoftwareTechnology, pull requests merged in 2022-04, with the labels that each got.

#12 First Implementation of Use-Cases
  Παραδοτέο_2/Use-cases-v0.1.docx
Labels: documentation

#13 Second use cases implementation
  Παραδοτέο_2/Use-cases-v0.1.docx
  Παραδοτέο_2/~$e-cases-v0.1.docx
  Παραδοτέο_2/~WRL0005.tmp
Labels: documentation

#15 Mock up artboards exports
  MockUps/Base/Event Check Ins.png
  MockUps/Base/Event Creation.png
  MockUps/Base/Event Reservations.png
  MockUps/Base/EventCheckIn.png
  MockUps/Base/LoginPage.png
  MockUps/Base/RoomCheckIn – 1.png
  MockUps/Base/RoomCheckIn.png
  MockUps/Base/StaffEvents – 5.png
  MockUps/Base/StaffHomePage.png
  MockUps/Base/Statistic.png
  MockUps/Base/Visitor-CreateReservation.png
  MockUps/Base/Visitor-Events.png
  MockUps/Base/Web 1920 – 1.png
  MockUps/Base/Web 1920 – 2.png
  MockUps/Base/Web 1920 – 3.png
  MockUps/Base/Web 1920 – 4.png
  MockUps/Base/Web 1920 – 5.png
  MockUps/Base/Web 1920 – 7.png
  MockUps/Base/Web 1920 – 9.png
  MockUps/Customer/CustomerEvents.png
  MockUps/Customer/CustomerRoom.png
  MockUps/HomePage.png
  MockUps/Palette.png
  MockUps/Staff/EventReservations/StaffEventReservations.png
  MockUps/Staff/EventReservations/StaffEventReservations_AddForm.png
  MockUps/Staff/Events/StaffEvents – 1.png
  MockUps/Staff/Events/StaffEvents – 2.png
  MockUps/Staff/Events/StaffEvents – 3.png
  MockUps/Staff/Events/StaffEvents – 4.png
  MockUps/Staff/Events/StaffEvents – 6.png
  MockUps/Staff/Events/StaffEvents.png
  MockUps/Staff/Login/StaffLogin.png
  MockUps/Staff/Login/StaffRegister.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn – 1.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn – 2.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn – 3.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn – 4.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn – 5.png
  MockUps/Staff/RoomCheckIn/StaffRoomCheckIn.png
  MockUps/Staff/Rooms/StaffRooms.png
  MockUps/Staff/Rooms/StaffRooms_CheckOut.png
  MockUps/Staff/Rooms/StaffRooms_Filters.png
Labels: design

#31 Diagrams Implementation
  Παραδοτέο_2/gant_diagram_project_v2.xlsx
  Παραδοτέο_2/gantt_diagram_paradotea_v2.xlsx
  Παραδοτέο_2/pert_diagram_paradotea_v2.xlsx
  Παραδοτέο_2/pertt_diagram_project_v2.xlsx
Labels: documentation

#36 Diagrams implementation
  Παραδοτέο_2/gant_diagram_project_v2.xlsx
  Παραδοτέο_2/gantt_diagram_project_names_v2.xlsx
  Παραδοτέο_2/pertt_diagram_project_v2.xlsx
Labels: diagrams

#51 Logo completion. Domain model implementation
  logo.png
  Παραδοτέο_2/Domain-model-v0.1.docx
  Παραδοτέο_2/Domain-model-v0.1.pdf
  Παραδοτέο_2/UML_VirtualReceptionist.afdesign
  Παραδοτέο_2/UML_VirtualReceptionist.pdf
  Παραδοτέο_2/UML_VirtualReceptionist.png
Labels: documentation, design, diagrams
