Repository PapKate/SoftwareTechnology, pull requests merged in 2022-06, with the labels that each got.

#76 ui code implementation
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.suo
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Hotel/RoomCheckIn.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Users/Customer.cs
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/VirtualReceptionist.dll
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/VirtualReceptionist.pdb
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/ref/VirtualReceptionist.dll
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/wwwroot/_framework/VirtualReceptionist.dll
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/wwwroot/_framework/VirtualReceptionist.dll.gz
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/wwwroot/_framework/VirtualReceptionist.pdb
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/wwwroot/_framework/VirtualReceptionist.pdb.gz
  App/VirtualReceptionist/VirtualReceptionist/bin/Debug/net6.0/wwwroot/_framework/blazor.boot.json
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/VirtualReceptionist.GeneratedMSBuildEditorConfig.editorconfig
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/VirtualReceptionist.csproj.CoreCompileInputs.cache
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/VirtualReceptionist.dll
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/VirtualReceptionist.pdb
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/blazor.boot.json
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/build-gz/ID8Z3efz.gz
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/build-gz/kUoG+wFw.gz
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/project.razor.json
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/ref/VirtualReceptionist.dll
  App/VirtualReceptionist/VirtualReceptionist/obj/staticwebassets.pack.sentinel
Labels: code

#78 Use cases 10 &11 code implementation
  App/VirtualReceptionist/VirtualReceptionist/Pages/Customer/CustomerEventsPage.razor
  App/VirtualReceptionist/VirtualReceptionist/Pages/Customer/CustomerEventsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Customer/CustomerReservationPayments.razor
  App/VirtualReceptionist/VirtualReceptionist/Pages/Customer/CustomerReservationPayments.razor.cs
Labels: code

#83 Final team-risk team-plan project-plan diagrams
  Παραδοτέο_6/1/Project-plan-v1.0.docx
  Παραδοτέο_6/1/Risk-assessment-v1.0.docx
  Παραδοτέο_6/1/Team-Risk-assessment-v1.0.docx
  Παραδοτέο_6/1/Team-plan-v1.0.docx
  Παραδοτέο_6/1/diagrams/gantt_diagram.xlsx
  Παραδοτέο_6/1/diagrams/gantt_diagram_2.xlsx
  Παραδοτέο_6/1/diagrams/pert.pdf
  Παραδοτέο_6/1/diagrams/pert_diagram.xlsx
Labels: documentation, diagrams

#95 Final Use-Cases Implementation
  Παραδοτέο_4/Use-cases-v0.3.docx
  Παραδοτέο_6/Use-cases-v1.0.docx
  Παραδοτέο_6/use-cases-diagram-v1.0.xlsx
Labels: documentation, diagrams

#97 sequence-diagrams-final
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-1.pdf
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-1.png
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-10.pdf
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-10.png
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-11.xlsx
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-3.pdf
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-3.png
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-5.pdf
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-5.png
  Παραδοτέο_6/Sequence-Diagrams/Sequence-Diagram-Use-Case-8.pdf
  Παραδοτέο_6/Sequence-Diagrams/Sequence-diagram-Use-Case-8.png
Labels: diagrams

#98 class and domain final
  Παραδοτέο_6/Class-Diagram/Class-Diagram-v1.0.pdf
  Παραδοτέο_6/Class-Diagram/Class-Diagrams-Pt.1.pdf
  Παραδοτέο_6/Class-Diagram/Class-Diagrams-Pt.1.png
  Παραδοτέο_6/Class-Diagram/Class-Diagrams-Pt.2.pdf
  Παραδοτέο_6/Class-Diagram/Class-Diagrams-Pt.2.png
  Παραδοτέο_6/Class-Diagram/UML_class_1.pdf
  Παραδοτέο_6/Class-Diagram/UML_class_1.png
  Παραδοτέο_6/Domain-Model/Domain-model-v1.0.docx
  Παραδοτέο_6/Domain-Model/Domain-model-v1.0.pdf
  Παραδοτέο_6/Domain-Model/Domain.docx
  Παραδοτέο_6/Domain-Model/VirtaulReceptionist-Pt.1.pdf
  Παραδοτέο_6/Domain-Model/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_6/Domain-Model/VirtaulReceptionist-Pt.2_1.pdf
  Παραδοτέο_6/Domain-Model/VirtaulReceptionist-Pt.2_1.png
Labels: diagrams

#99 Final Sequence 4,9
  Παραδοτέο_6/Sequence-Diagrams/sequence-diagram-pt1-use-case-4.xlsx
  Παραδοτέο_6/Sequence-Diagrams/sequence.d.4(part 2).pdf
  Παραδοτέο_6/Sequence-Diagrams/sequence.d.4(part 2).png
  Παραδοτέο_6/Sequence-Diagrams/sequence.d_9.pdf
  Παραδοτέο_6/Sequence-Diagrams/sequence_9.png
Labels: diagrams

#100 Final Code Implementation
  App/VirtualReceptionist/.vs/ProjectEvaluation/virtualreceptionist.metadata.v2
  App/VirtualReceptionist/.vs/ProjectEvaluation/virtualreceptionist.projects.v2
  App/VirtualReceptionist/.vs/VirtualReceptionist/DesignTimeBuild/.dtbcache.v2
  App/VirtualReceptionist/.vs/VirtualReceptionist/FileContentIndex/6f597378-3241-406c-9d78-1bad3ac42da3.vsidx
  App/VirtualReceptionist/.vs/VirtualReceptionist/FileContentIndex/c13085a0-f416-4179-a3fe-768c91b39982.vsidx
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.suo
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffEventReservationsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffEventsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffRoomPaymentsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Shared/HelperMethods.cs
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net6.0/project.razor.vs.json
  Παραδοτέο_6/Robustness-Diagrams/robustness_use-case-9.xlsx
Labels: code

#101 class and domain final
  Παραδοτέο_6/Class-Diagram/Class.docx
  Παραδοτέο_6/Class-Diagram/UML_class.pdf
  Παραδοτέο_6/Class-Diagram/UML_class.png
  Παραδοτέο_6/Class-Diagram/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_6/Class-Diagram/VirtaulReceptionist-Pt.2.png
  Παραδοτέο_6/Domain-Model/UML_class_1.pdf
  Παραδοτέο_6/Domain-Model/UML_class_1.png
Labels: documentation, diagrams
