Repository PapKate/SoftwareTechnology, pull requests merged in 2022-05, with the labels that each got.

#53 Diagrams implementation
  Παραδοτέο_3/Διαγράμματα/Use-cases-v0.2.docx
  Παραδοτέο_3/Διαγράμματα/robustness-diagram-customer (1).xlsx
Labels: diagrams

#54 final robustness staff and visitor
  Παραδοτέο_3/Διαγράμματα/robustness-diagram-staff.xlsx
  Παραδοτέο_3/Διαγράμματα/robustness-diagram-visitor.xlsx
Labels: diagrams

#55 Pap kate vol.7
  Παραδοτέο_3/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_3/VirtualReceptionist.pdf
Labels: diagrams

#56 Domian model modifications and report
  Παραδοτέο_2/Domain-model-v0.1.docx
  Παραδοτέο_3/DomainModel/Domain-model-v0.2.docx
  Παραδοτέο_3/DomainModel/Domain-model-v0.2.pdf
  Παραδοτέο_3/DomainModel/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_3/DomainModel/VirtaulReceptionist-Pt.2.png
  Παραδοτέο_3/DomainModel/VirtualReceptionist.pdf
  Παραδοτέο_3/DomainModel/VirtualReceptionist.png
  Παραδοτέο_3/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_3/VirtualReceptionist.pdf
Labels: documentation, diagrams

#57 Use_cases_Vol.3
  Παραδοτέο_4/Use-cases-v0.3.docx
Labels: documentation

#58 update use-cases.v0.3
  Παραδοτέο_4/Use-cases-v0.3.docx
Labels: documentation

#62 reservationw-events-code
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/CustomerEventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/Event.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventChekcIn.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Reviews/Review.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Reviews/RoomReview.cs
Labels: code

#64 Domain model v0.3 implementation
  App/VirtualReceptionist/.vs/VirtualReceptionist/DesignTimeBuild/.dtbcache.v2
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.futdcache.v1
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.suo
  App/VirtualReceptionist/VirtualReceptionist/Models/Hotel/Facility.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Hotel/Hotel.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Hotel/Room.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Reviews/RoomReview.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Users/Staff.cs
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net5.0/VirtualReceptionist.csproj.AssemblyReference.cache
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net5.0/project.razor.json
  Παραδοτέο_4/DomainModel/Domain-model-v0.3.docx
  Παραδοτέο_4/DomainModel/Domain-model-v0.3.pdf
  Παραδοτέο_4/DomainModel/VirtaulReceptionist-Pt.1.pdf
  Παραδοτέο_4/DomainModel/VirtaulReceptionist-Pt.2.pdf
  Παραδοτέο_4/UML_class.pdf
  Παραδοτέο_4/VirtaulReceptionist-Pt.2.pdf
Labels: documentation, diagrams, code

#65 sequence diagrams use cases 1, 3, 10
  Παραδοτέο_4/Diagrams/sequence_1.pdf
  Παραδοτέο_4/Diagrams/sequence_10.pdf
  Παραδοτέο_4/Diagrams/sequence_3.pdf
  Παραδοτέο_4/Use-cases-v0.3.docx
Labels: diagrams

#66 sequence diagrams
  Παραδοτέο_4/Diagrams/Sequence/sequence_1.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_10.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_3.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_4_part1.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_9.pdf
Labels: diagrams

#67 Sequence Diagram Implementation
  Παραδοτέο_4/Diagrams/Sequence/sequence_11.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_5.pdf
  Παραδοτέο_4/Diagrams/Sequence/sequence_8.pdf
Labels: diagrams

#71 use case 1 code implementation
  App/VirtualReceptionist/.vs/VirtualReceptionist/DesignTimeBuild/.dtbcache.v2
  App/VirtualReceptionist/.vs/VirtualReceptionist/project-colors.json
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.futdcache.v1
  App/VirtualReceptionist/.vs/VirtualReceptionist/v17/.suo
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/Event.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventChekcIn.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/VisitorEventsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Shared/HelperMethods.cs
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net5.0/VirtualReceptionist.RazorComponent.input.cache
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net5.0/VirtualReceptionist.csproj.AssemblyReference.cache
  App/VirtualReceptionist/VirtualReceptionist/obj/Debug/net5.0/project.razor.json
  Παραδοτέο_4/~$e-cases-v0.3.docx
Labels: code

#72 4,5 Use Cases Code Implementation
  App/VirtualReceptionist/VirtualReceptionist/Enums/PaymentType.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventChekcIn.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/EventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Reviews/RoomReview.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Customer/CustomerMyRoomPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffEventsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/VisitorEventsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Shared/HelperMethods.cs
  Παραδοτέο_4/Use-cases-v0.3.docx
Labels: documentation, code

#74 Use cases 8 & 9 code implementation
  App/VirtualReceptionist/VirtualReceptionist/Models/Events/CustomerEventReservation.cs
  App/VirtualReceptionist/VirtualReceptionist/Models/Users/CustomerUser.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffEventReservationsPage.razor.cs
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffRoomPaymentsPage.razor
  App/VirtualReceptionist/VirtualReceptionist/Pages/Staff/StaffRoomPaymentsPage.razor.cs
Labels: code
